#pragma once

const int
	DIFFICULTY_LEVELS = 3,
	BEGINNER_ROWS = 10,
	BEGINNER_COLS = 10,
	BEGINNER_MINES = 10,

	INTERMEDIATE_ROWS = 18,
	INTERMEDIATE_COLS = 14,
	INTERMEDIATE_MINES = 40,

	EXPERT_ROWS = 28,
	EXPERT_COLS = 18,
	EXPERT_MINES = 99,

	BEGINNER_CELL_SIZE = 50,
	INTERMEDIATE_CELL_SIZE = 45,
	EXPERT_CELL_SIZE = 40,

	START_WINDOW_BUTTONS_NUMBER = 4,
	BUTTON_WIDTH = 300,
	BUTTON_HEIGHT = 50;